# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/continex/RVfpgaSoC/RVfpgaSoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_my_mic_0_0/swerv_soc_my_mic_0_0.xci
# IP: The module: 'swerv_soc_my_mic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/continex/RVfpgaSoC/RVfpgaSoC.srcs/sources_1/bd/Xilinx/Vivado/lab_src/rtl_src/my_mic.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_my_mic_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/continex/RVfpgaSoC/RVfpgaSoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_my_mic_0_0/swerv_soc_my_mic_0_0.xci
# IP: The module: 'swerv_soc_my_mic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/continex/RVfpgaSoC/RVfpgaSoC.srcs/sources_1/bd/Xilinx/Vivado/lab_src/rtl_src/my_mic.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_my_mic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
